### ISSUE TITLE
S3Connector - use subtype instead of newtype and refactor out redundant _.toString calls

### ISSUE THREAD

**Issue by adrianfilip** [zio/zio-connect#103]
The existing implementation uses subtype for the connector domain types. This leads to a lot of use of _.toString. We could achieve the same level of typesafety with Subtype and without having to call _.toString everythere.

The new implementation would look like this
```
  object BucketName extends Subtype[String] //previously was Newtype[String]
  type BucketName = BucketName.Type

  object ObjectKey extends Subtype[String] //previously was Newtype[String]
  type ObjectKey = ObjectKey.Type
```

**Comment by irach-ramosh** [comment]
I would like to work on this issue.

**Comment by adrianfilip** [comment]
https://github.com/zio/zio-connect/pull/104
