### ISSUE TITLE
DynamoDBConnector - new connector

### ISSUE THREAD

**Issue by adrianfilip** [zio/zio-connect#91]
#Steps
- [ ] Add a new project
-- Example: https://github.com/zio/zio-connect/blob/2507925dcd9acf5cb1dbb5e004afef3982ad6807/build.sbt#L38
- [ ] Create the following directory structure

         zio.connect.dynamobd
         
- [ ] Create the connector

       
       sealed trait DynamoDBConnector
      
       case class AWSDynamoDBConnector() extends DynamoDBConnector { ... }
       
       object AWSDynamoDBConnector {
           val layer: ZLayer[???, ???, DynamoDBConnector] = {
               ...
               AWSDynamoDBConnector()
           }

       }

- [ ] Provide accessors in the package object
        Example: https://github.com/zio/zio-connect/blob/master/connectors/file-connector/src/main/scala/zio/connect/file/package.scala

- [ ] Tests belong in the DynamoDBConnectorSpec file. 
        They use the accessors. 
        Example:- https://github.com/zio/zio-connect/blob/master/connectors/file-connector/src/test/scala/zio/connect/file/FileConnectorSpec.scala

- [ ] There will be a AWSDynamoDBConnectorSpec that runs the DynamoDBConnectorSpec files for the AWSDynamoDBConnector layer
     You can use it with localstack testcontainers.
      Example with testcontainers and S3 here -  https://github.com/zio/zio-connect/pull/83/files#diff-e7e0899e455a741a644a05c0b26879d176a9126951477cd7c62dc19ade98b5cc
      

- [ ] Provide a TestDynamoDBConnector layer that allows testing with a stub.
Example - https://github.com/zio/zio-connect/blob/master/connectors/file-connector/src/main/scala/zio/connect/file/TestFileConnector.scala

**Comment by grouzen** [comment]
I would like to pick up this one.

**Comment by ASRagab** [comment]
@adrianfilip would like to give this a try?
